# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-modify_date',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(default='Nothing', verbose_name='CONTENT'),
        ),
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.CharField(blank=True, default='Nothing', help_text='simple description text.', max_length=500, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='posts',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify Date'),
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='one word for title alias', null=True, unique=True, verbose_name='SLUG'),
        ),
    ]
